from . import et_course_tag
from . import et_course_index
from . import et_course
from . import et_session
from . import et_session_attendance
from . import hr_employee
from . import et_course_index
from . import project_task
from . import et_course_certificate
from . import training_dashboard
